<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $template['name'] }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; }
        h1 { font-size: 24px; font-weight: bold; margin-bottom: 24px;}
        p { margin-bottom: 10px;}
        .small { font-size: 14px; color: #888;}
    </style>
</head>
<body>
    <h1>{{ $template['name'] }}</h1>
    <pre>{{ $documentText }}</pre>
    <div class="small">Generated by Lawza App</div>
</body>
</html>