<?php
return [
    ['key' => 'sale_deed', 'name' => 'Sale Deed', 'description' => 'Deed for sale/transfer of property.'],
    ['key' => 'agreement_to_sell', 'name' => 'Agreement to Sell', 'description' => 'Preliminary agreement before actual sale deed.'],
    ['key' => 'gift_deed', 'name' => 'Gift Deed', 'description' => 'Transfer of property by way of gift.'],
    ['key' => 'general_power_of_attorney', 'name' => 'General Power of Attorney', 'description' => 'Authorise someone for general powers related to property.'],
    ['key' => 'special_power_of_attorney', 'name' => 'Special Power of Attorney', 'description' => 'Specific power to act for particular property matter.'],
    ['key' => 'irrevocable_power_of_attorney', 'name' => 'Irrevocable Power of Attorney', 'description' => 'Permanent, cannot be revoked without consent.'],
    ['key' => 'lease_deed', 'name' => 'Lease Deed', 'description' => 'Grant lease right for defined period.'],
    ['key' => 'rent_agreement', 'name' => 'Rent Agreement', 'description' => 'Standard residential/commercial rental agreement.'],
    ['key' => 'exchange_deed', 'name' => 'Exchange Deed', 'description' => 'Deed for exchange of two properties.'],
    ['key' => 'mortgage_deed', 'name' => 'Mortgage Deed', 'description' => 'Property mortgaged for securing a loan.'],
    ['key' => 'affidavit', 'name' => 'Affidavit/Declaration', 'description' => 'Affidavit for land-related undertakings.'],
    ['key' => 'partition_deed', 'name' => 'Partition Deed', 'description' => 'Partition among co-owners or heirs.'],
    ['key' => 'relinquishment_deed', 'name' => 'Relinquishment Deed', 'description' => 'Release share by co-owner/heir.'],
    ['key' => 'mutation_request', 'name' => 'Mutation Application', 'description' => 'Mutation and transfer application for revenue records.'],
    ['key' => 'building_plan_approval', 'name' => 'Building Plan Approval Application', 'description' => 'Request for sanction of construction.'],
    ['key' => 'allotment_letter', 'name' => 'Allotment Letter', 'description' => 'Issued by housing societies or builders.'],
    ['key' => 'transfer_letter', 'name' => 'Transfer Letter', 'description' => 'Transfer of society/authority property.'],
    ['key' => 'possession_letter', 'name' => 'Possession Letter', 'description' => 'Handover certificate of property.'],
    ['key' => 'noc_for_sale', 'name' => 'No Objection Certificate (NOC)', 'description' => 'NOC for sale or transfer from society/authority.'],
    ['key' => 'indemnity_bond', 'name' => 'Indemnity Bond', 'description' => 'For loss of documents/disputes.'],
    ['key' => 'assignment_deed', 'name' => 'Assignment Deed', 'description' => 'Assign property rights.'],
    ['key' => 'dissolution_joint_ownership', 'name' => 'Dissolution of Joint Ownership', 'description' => 'End joint property ownership.'],
    ['key' => 'cancellation_deed', 'name' => 'Cancellation Deed', 'description' => 'Cancel original registry/agreement.'],
    ['key' => 'agreement_for_construction', 'name' => 'Agreement for Construction', 'description' => 'With contractor/builder.'],
    ['key' => 'advance_receipt', 'name' => 'Advance Receipt', 'description' => 'Acknowledge advance payment.'],
    ['key' => 'succession_certificate', 'name' => 'Succession/Heirship Certificate', 'description' => 'For inheritance/succession.'],
    ['key' => 'will_testament', 'name' => 'Will/Testament', 'description' => 'Bequeath specific property.'],
    ['key' => 'eviction_notice', 'name' => 'Eviction/Legal Notice to Tenant', 'description' => 'For default/eviction proceedings.'],
];